[book]
authors = ["J.T. Wolohan"]
language = "en"
multilingual = false
src = "src"
title = "Super Dead"

[build]
build-dir = "docs"
create-missing = false

[output.html]
# additional-css = ["custom.css"]

[output.html.search]
limit-results = 20